name: Deploy to S3

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_KEY }}
          aws-region: eu-central-1  # change to your region

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync ./ s3://martin-web --delete
